### ISSUE TITLE
generator: allow to import settings from gluon site.conf

### ISSUE THREAD

**Issue by saerdnaer** [freifunk/api.freifunk.net#115]
Some information is already machine readable in the gluon site.conf file. Maybe it is a good idea to give to allow to import this information in the generator. Here is a list of site.conf repos from different communities:

* [Hamburg](https://github.com/freifunkhamburg/site-ffhh/blob/master/site.conf)
* [Lübeck](https://github.com/freifunk-gluon/site-ffhl/blob/master/site.conf)
* [Mainz](https://github.com/Freifunk-Mainz/site-ffmz/blob/master/site.conf)
* [Oldenburg](http://git.freifunk-ol.de/root/siteconf/blob/master/site.conf)
* [Paderborn](https://git.c3pb.de/freifunk-pb/site-ffpb/blob/master/site.conf)
* [München](https://github.com/freifunkMUC/site-ffm/blob/master/site.conf)

Update see https://github.com/freifunk-gluon/gluon/blob/master/docs/user/site.rst#site-repos-in-the-wild for a bigger list

**Comment by FreifunkUFO** [comment]
im Generator macht das wahjrscheinlich wenig Sinn.. lieber direkt in der API, siehe extra-Ticket
