### ISSUE TITLE
specs: add comment/description field to donation information

### ISSUE THREAD

**Issue by mweinelt** [freifunk/api.freifunk.net#120]
There are times when we need to mentions things like appropriation, which needs to be mentioned in the bank transaction to have the money properly addressed to us. 

There is currently no field to reflect that.

**Comment by mojoaxel** [comment]
With bbf2331 I've added a proposal. If you like it we can deploy a new version of the specs.

**Comment by mojoaxel** [comment]
@andibraeu What do you think should we release a new version for this or wait for more changes?

**Comment by mweinelt** [comment]
We are not in a hurry, as we do not know of any services using this data, yet. So take your time.

**Comment by andibraeu** [comment]
I think it's ok!
