### ISSUE TITLE
generator: map improvements

### ISSUE THREAD

**Issue by mojoaxel** [freifunk/api.freifunk.net#135]
the generator has a nice new map to set the communities location. i think some improvements could be done:
- we should cange the tile source of the background map. these renderer seams to only render some citynames and no street information or landuse or something to help you orientate. we could use default osm here.
- the size of the map is to small. there is room, to the right.
- it would be nice if the map could be displayed on the top of the location section instead of at the end.
- it would be relativel easy to determan country and city name after the user sets the coordinates. see http://stackoverflow.com/questions/18487957/how-to-get-the-city-name-by-latitude-and-longitude-using-openstreetmap-in-androi

**Comment by Nau56** [comment]
Can I work of this bug

**Comment by mojoaxel** [comment]
> Can I work of this bug

@Nau56 What would you like to implement?

**Comment by andibraeu** [comment]
I think this issue is obsolete, as we rewrote the generator some years ago. see https://github.com/freifunk/generator.api.freifunk.net

**Comment by Nau56** [comment]
If you have any types of issues then you can definitely contact me sir. I
want to help you

**Comment by mojoaxel** [comment]
Thanks, @Nau56 but I also think this issue is obsolete.
