### ISSUE TITLE
descriptive typo in all api versions

### ISSUE THREAD

**Issue by SimJoSt** [freifunk/api.freifunk.net#137]
In the section "Technical Details" under "Domain Names" the descriptive sentence "Nameservers servings zones of your domain" got a typo.
Correct would be "serving zones", without the second 's' in serving.

As I don't know how old api versions are maintained I opened an issue instead of pr.

**Comment by andibraeu** [comment]
just add it to the development.json and we'll solve it with the next version

**Comment by SimJoSt** [comment]
Sure thing @andibraeu :-)
I did in #140
