### ISSUE TITLE
bremen.json file is not shown correctly in generator, but works on all other parts of api

### ISSUE THREAD

**Issue by SimJoSt** [freifunk/api.freifunk.net#149]
The [bremen.json file](https://bremen.freifunk.net/ffapi/bremen.json) is valid 0.4.14 version freifunk api file, according to the generator, when I paste and validate it, and the [api viewer](https://api-viewer.freifunk.net/). According to the latter everything is fine and the loading of the api file poses no problems.

But if I let it be loaded through the dropdown menu in the generator, it's contents are [not correctly shown](https://gist.github.com/SimJoSt/40afbb11bf01cacee68ae4090afcd0b7). One of our admins assumed it has something to do with our setup of https, so maybe it's possible to fix it on our end.

But it seems to me, that different loading behaviours on different parts of the freifunk api sofware is not desirable.

**Comment by SimJoSt** [comment]
This might be solved with https://github.com/freifunk/directory.api.freifunk.net/pull/483
Though the generator should handle a http to https redirect properly.

**Comment by andibraeu** [comment]
works now. the generator uses a php proxy and javascript to load the files. I'm not sure if redirects can be handled better
