### ISSUE TITLE
contact: mastodon

### ISSUE THREAD

**Issue by OLeier** [freifunk/api.freifunk.net#168]
Bei der Schema Validierung ist dieser Fehler aufgetreten:
`Property 'mastodon' has not been defined and the schema does not allow additional properties. Path 'contact.mastodon', line 20, position 17.`
Da die Nutzung von Mastodon sicherlich kein Fehler ist, müsste das Schema um diesen Kontakt Typ erweitert werden.
Wäre das dann in der Version 0.5.1?

**Comment by andibraeu** [comment]
done in d77b97c576bf39ec59f5d0c3940e6b2dba33436d
