### ISSUE TITLE
Node APIs

### ISSUE THREAD

**Issue by monic2001** [freifunk/api.freifunk.net#33]
Liste von einer bzw. mehreren API URLs und der dort jeweils verwendeten API-Formats, d.h. dass Einsprungpunkte bereitgestellt/announciert werden können, an denen in definierten APIs Informationen zu Knoten der jeweiligen Netze bereitgestellt werden.

Ziel: alle communities können die Nodedaten der anderen nutzen, um sie in ihrer Kartenlösung darzustellen bzw. es können übergreifende Karten entstehen.

**Comment by mojoaxel** [comment]
Ich denke wir können nach 6caac28100ad84f6cbb7d1fa8c03481f2df153e0 das Issue jetzt erstmal schließen.
