### ISSUE TITLE
Generator: Use api specs from the specs folder

### ISSUE THREAD

**Issue by mojoaxel** [freifunk/api.freifunk.net#67]
The api specs are in the _specs_ folder. The generator should use these files instead of depending on a copy of these files.

**Comment by christian-weiss** [comment]
I would welcome to have a single location for specs only.

Would be cool to drop them from here:
https://github.com/freifunk/api.freifunk.net/blob/master/generator/0.*.json
example:
https://github.com/freifunk/api.freifunk.net/blob/master/generator/0.1.json

And use always these files:
https://github.com/freifunk/api.freifunk.net/blob/master/specs/0.*.json
example:
https://github.com/freifunk/api.freifunk.net/blob/master/specs/0.1.json

I dislike redundancy ;-)

**Comment by christian-weiss** [comment]
I filed a PR to get rid of these files.
